---
title: "Environmental Non-Profits in Texas from 2013-2018"
output: html_notebook
---



```{r, loading data & libraries}
library(tidyverse)
library(ggmap)
library(janitor)
library(rgdal)
library(mapproj)
library(maptools)
library(dplyr)
library(sf)
library(viridis) # nice color palette
library(ggplot2) # plotting
library(ggmap) # ggplot functionality for maps
library(dplyr) # use for fixing up data
library(readr) # reading in data/csv
library(RColorBrewer) # for color palettes
library(purrr) # for mapping over a function
library(magick)
library(maps)
library(ggplot2)
library(plotly)

df <- read.csv("texas_20132018_envorgs_matched.csv")
df <- clean_names(df)
df <- dplyr::select(df, ein, real_year, taxpayer_name, name, address, city, state, zip5, fips, assets, income)


#county_map <- readOGR("Texas_County_Boundaries_Detailed.shp")
#county_map@data <- clean_names(county_map@data)
```


```{r,Preprocessing}

df_filled <- df %>% group_by(ein) %>% fill(taxpayer_name) %>% fill(taxpayer_name, .direction = "up") %>% fill(address) %>% fill(address, .direction = "up") %>% fill(city) %>% fill(city, .direction = "up") %>% fill(state) %>% fill(state, .direction = "up")

#df_filled <- df_filled %>% mutate_all(na_if,"")
df_filled$taxpayer_name <- as.character(df_filled$taxpayer_name)
df_filled$name <- as.character(df_filled$name)
df_filled$address <- as.character(df_filled$address)
df_filled$city <- as.character(df_filled$city)
df_filled$state <- as.character(df_filled$state)
          
for (i in 1:length(df_filled$taxpayer_name)){
           if(df_filled$taxpayer_name[i] == ""){        
                    df_filled$taxpayer_name[i] <- df_filled$name[i]              
           }
}

for (i in 1:length(df_filled$taxpayer_name)){
           if(is.na(df_filled$taxpayer_name[i])){        
                    df_filled$taxpayer_name[i] <- df_filled$name[i]              
           }
}


df_filled <- select(df_filled, ein, real_year, taxpayer_name,address, city, state, zip5, fips, assets, income)


df_filled <- filter(df_filled, address != "")
df_filled <- mutate(df_filled, full_address = paste(address, city, state, sep = ", "))
df_filled <- mutate(df_filled, full_address2 = paste(full_address, zip5))
df_filled <- select(df_filled, ein, real_year, taxpayer_name, full_address2, fips, assets, income)
df_filled <- rename( df_filled, address = full_address2, name = taxpayer_name)

for (i in 1:length(df_filled$assets)){
           if(df_filled$assets[i] == 0){        
                    df_filled$assets[i] <- 1              
           }
}
```

```{r, geocoding}

geocoded_df2017 <- df_filled %>% filter(real_year == 2017) %>% mutate_geocode(address)
#geocoded_df <- df_filled %>% mutate_geocode(address)


#write.csv(geocoded_df,"geocoded_df.csv")

```

```{R, group by county}

df_county <- df_filled %>% group_by(real_year, fips) %>% summarize(total_assets = sum(assets), total_income = sum(income))

```

```{R, map}



geocoded_df2017$name <- as.factor(geocoded_df2017$name)

geocoded_df2017 <- geocoded_df2017 %>% arrange(desc(assets)) 



options("scipen"=100, "digits"=0)
tx <- get_map(
  #location='texas',
  c(lon=-100.253489,lat=30.844382),
  zoom=6,crop=T,
  scale="auto",color="bw",source="google",
  maptype="terrain") # can change to terrain

gg <- ggmap(tx, extent='panel',padding=0) 

map <- gg + geom_point(data = geocoded_df2017, aes(x=lon, y=lat, size=assets, color=assets, alpha=0.5), shape=20, stroke=4) + scale_color_viridis(option="viridis", trans="log", name="Assets in log $", direction = -1) + ggtitle("Distribution of Environmental NPO's in 2017 (By asset size)") +guides(alpha = FALSE, size = FALSE) + theme(legend.position=c(.9,.15) , panel.grid = element_blank(),axis.title.y = element_blank(), axis.title.x = element_blank(), axis.ticks = element_blank(), rect = element_blank(), plot.title = element_text(size= 25, vjust = 1, hjust= 0.1, color = "#060418FF", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")), plot.background = element_rect(fill = "#f5f5f2", color = NA), panel.background = element_rect(fill = "#f5f5f2", color = NA), legend.background = element_rect(fill = "#f5f5f2", color = NA),) + theme_void()
   
map     
        


```

```{r, Plotly}

# Rorder data + Add a new column with tooltip text
geocoded_plotly <- 
  mutate(geocoded_df2017, mytext=paste(
    "NPO Name: ", name, "\n", 
    "Assets: $", assets, sep="")
  )

# Make the map (static)
map_plotly <- gg + geom_point(data = geocoded_plotly, aes(x=lon, y=lat, size=assets, color=assets, alpha=0.5, text =mytext), shape=20, stroke=1) + scale_color_viridis(option="viridis", trans="log", name="Assets in log $", direction = -1) + ggtitle("Distribution of Environmental NPO's in 2017 (By asset size)") +guides(alpha = FALSE, size = FALSE) + theme(legend.position=c(.9,.15) , panel.grid = element_blank(),axis.title.y = element_blank(), axis.title.x = element_blank(), axis.ticks = element_blank(), rect = element_blank(), plot.title = element_text(size= 25, vjust = 1, hjust= 0.1, color = "#060418FF", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")), plot.background = element_rect(fill = "#f5f5f2", color = NA), panel.background = element_rect(fill = "#f5f5f2", color = NA), legend.background = element_rect(fill = "#f5f5f2", color = NA),) + theme_void()

map_plotly <- ggplotly(map_plotly, tooltip="text")

map_plotly

# save the widget in a html file if needed.
library(htmlwidgets)
htmlwidgets::saveWidget(map_plotly, file="environmental_npos_texas.html", selfcontained = FALSE)

```